### ISSUE TITLE
User Story - Correct Answer on Quiz

### ISSUE THREAD

**Issue by Dee-McG** [Dee-McG/Hackathon-July-2024#16]
As a user I want to know when I got the answer correct

**Acceptance Criteria**

- Correct answer is reflected to user

**Tasks**

- [ ] Create an event listener on flag clicks
- [ ] If the user answers wrong highlight red
- [ ] If the answer is right, highlight green
- [ ] Display fun fact after questions answered
